### ISSUE TITLE
Add another way to open the left sidebar

### ISSUE THREAD

**Issue by FliegendeWurst** [FliegendeWurst/TriliumDroid#4]
Opening the left sidebar might interfere with the "go back" gesture.

_Originally posted by @FliegendeWurst in https://github.com/FliegendeWurst/TriliumDroid/issues/2#issuecomment-2526276491_

**Comment by FliegendeWurst** [comment]
Fixed for next release

**Comment by MatejPetrik007** [comment]
Thanks for the Alpha

finally i can open notes but the UI for the gestures is still not there yet the app cant inicialize the bar for gesture mode on P7PRO
![image](https://github.com/user-attachments/assets/399f242e-100b-4760-b4a5-5e662b01c63b)

on One Plus 5 without gestures its working fine
![image](https://github.com/user-attachments/assets/9abc02b4-f3fa-4775-9e89-2e9b6393a2e9)
