### ISSUE TITLE
Images in notes don't fit into moving page widths

### ISSUE THREAD

**Issue by yggcwx** [FliegendeWurst/TriliumDroid#46]
The image in the note does not fit the width of the mobile page: the image in the app will extend from the mobile page to exceed the width of the current page.

**Comment by FliegendeWurst** [comment]
Thank you for the report.

I am aware of several more issues related to images.

- Alignment (left / right) is not preserved correctly
- Loads incorrectly in the editor view

**Comment by FliegendeWurst** [comment]
It is not yet fixed, since I'm not very familiar with the HTML editor component I'm using.

**Comment by yggcwx** [comment]
> It is not yet fixed, since I'm not very familiar with the HTML editor component I'm using.

It doesn't matter, as long as it can be repaired later, I look forward to early success! Can you consider recruiting some volunteers to join the app development team?

**Comment by yggcwx** [comment]
Excuse me, hasn't this bug been fixed yet? Hurry up

**Comment by FliegendeWurst** [comment]
So I had another look:

- viewing images directly works fine
- included images in other notes do not render at all.

Will try to fix in Alpha 8, hopefully

**Comment by yggcwx** [comment]
> So I had another look:
> 
> * viewing images directly works fine
> * included images in other notes do not render at all.
> 
> Will try to fix in Alpha 8, hopefully

That's great, thank you so much!

**Comment by FliegendeWurst** [comment]
This should be fixed with Alpha 8, at least in the cases I have tested. Let me know if you still have trouble.

**Comment by yggcwx** [comment]
> This should be fixed with Alpha 8, at least in the cases I have tested. Let me know if you still have trouble.

It has been confirmed: this issue is in the Alpha 9 version and is still not fixed! Please see the screenshot.

![Image](https://github.com/user-attachments/assets/00e6ccdf-bbaf-4c26-bcfe-c41f5e0e46b9)
![Image](https://github.com/user-attachments/assets/97a276cc-7aa8-4016-9bc7-1a421fd5de6c)

**Comment by FliegendeWurst** [comment]
Those images weren't added via the new attachments mechanism, right? I'll have to see if I can support the old method as well.

**Comment by yggcwx** [comment]
> Those images weren't added via the new attachments mechanism, right? I'll have to see if I can support the old method as well.

This is a web article that was previously saved via a browser clipping plugin.

这是之前通过浏览器剪藏插件保存的网页文章。

**Comment by FliegendeWurst** [comment]
I've implemented a potential solution in Alpha 10, released now.
I couldn't precisely reproduce your issue, so I am not certain it fixes the issue completely.

**Comment by yggcwx** [comment]
> I've implemented a potential solution in Alpha 10, released now. I couldn't precisely reproduce your issue, so I am not certain it fixes the issue completely.

Very good, almost perfect! Only a few pictures were slightly distorted, and in general, it did not affect normal reading. Thank you so much!

![Image](https://github.com/user-attachments/assets/264cf46f-31ed-418d-b674-f0a044fba8f2)
![Image](https://github.com/user-attachments/assets/d9d56f10-2ae6-4e77-be70-07818d653988)
![Image](https://github.com/user-attachments/assets/6367bdfe-2967-4f8d-92e8-b49c771fafcb)
